"""Add relationships

Revision ID: 026d5c28dd8c
Revises: 7d7a9afd1f6a
Create Date: 2024-07-11 00:33:28.058621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026d5c28dd8c'
down_revision = '7d7a9afd1f6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classification_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'classifications', ['classification_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('classification_id')

    # ### end Alembic commands ###
