"""Create tables

Revision ID: 7d7a9afd1f6a
Revises: 
Create Date: 2024-07-11 00:30:35.397030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7a9afd1f6a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geographic_location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number_of_speakers', sa.Integer(), nullable=False),
    sa.Column('country_of_origin', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ALIVE', 'ENDANGERED', 'DEAD', 'EXTINCT', name='status_enum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages')
    op.drop_table('classifications')
    # ### end Alembic commands ###
